include:
  - board: seeed_xiao_ble           # ここを修正
    shield: lalapad_right rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeed_xiao_ble           # ここを修正
    shield: lalapad_left rgbled_adapter
  - board: seeed_xiao_ble           # ここを修正
    shield: settings_reset
