include:
  - board: xiao_ble
    shield: lalapad_right rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: xiao_ble
    shield: lalapad_left rgbled_adapter
  - board: xiao_ble
    shield: settings_reset
